### ISSUE TITLE
Batch create form appears incorrectly

### ISSUE THREAD

**Issue by guycall** [activescaffold/active_scaffold_batch#4]
Following on from my previous issue. My app is:
 * Rails 4.0.x
 * Ruby 2.1
 * active_scaffold_batch 3.3.2 (git revision: revision: 25c0b82d624a2f6dc730e5281f9d6beb1dedb5e2)
 * active_scaffold 3.4.30

The batch create form now opens. However names do not correctly appear in the multiple select. They appear like "#Unit:0x007f77adbffcd0" and on submitting the form I get the error:

    ActiveRecord::RecordNotFound (Couldn't find all Units with IDs (#<Unit:0x007f77adb7f0a8>, #<Unit:0x007f77adbffcd0>) (found 0 results, but was looking for 2)):
      activerecord (4.0.13) lib/active_record/relation/finder_methods.rb:199:in `raise_record_not_found_exception!'
      activerecord (4.0.13) lib/active_record/relation/finder_methods.rb:308:in `find_some'
      activerecord (4.0.13) lib/active_record/relation/finder_methods.rb:272:in `find_with_ids'
      activerecord (4.0.13) lib/active_record/relation/finder_methods.rb:36:in `find'
      activerecord-deprecated_finders (1.0.4) lib/active_record/deprecated_finders/relation.rb:122:in `find'

If I inspect the HTML of the multiple select. Instead of seeing something like:

    <option value="316">Unit 123</option>

I see:

    <option value="#<Unit:0x007f77adbffcd0>">#&lt;Unit:0x007f77adbffcd0&gt;</option>

**Comment by guycall** [comment]
Just in case it is related i see there is a deprecation warning when I view the batch create form:

    ApplicationController::current_user
      [1m[36mUser Load (0.3ms)[0m  [1mSELECT `users`.* FROM `users` WHERE `users`.`id` = 4 LIMIT 1[0m
      Rendered /var/lib/gems/2.1.0/gems/active_scaffold-3.4.30/app/views/active_scaffold_overrides/_form_messages.html.erb (2.4ms)
      Rendered /home/vagrant/.bundler/ruby/2.1.0/active_scaffold_batch-25c0b82d624a/app/views/active_scaffold_overrides/_form_messages.html.erb (9.6ms)
    DEPRECATION WARNING: Relying on @record is deprecated, call with record. (called from active_scaffold_batch_create_singular_association at /home/vagrant/.bundler/ruby/2.1.0/active_scaffold_batch-25c0b82d624a/lib/active_scaffold/helpers/batch_create_column_helpers.rb:22)
      [1m[35mUnit Load (1.0ms)[0m  SELECT `units`.* FROM `units`

**Comment by guycall** [comment]
I ran a debug and this line https://github.com/activescaffold/active_scaffold_batch/blob/master/lib/active_scaffold/helpers/batch_create_column_helpers.rb#L22 gives an array of records. Where as in the vho version https://github.com/vhochstein/active_scaffold_batch/blob/master/lib/active_scaffold/helpers/batch_create_column_helpers.rb#L20 it returns a collection of (id, label) pairs - http://www.rubydoc.info/gems/active_scaffold_vho/3.0.16/ActiveScaffold/Helpers/AssociationHelpers:options_for_association

**Comment by scambra** [comment]
sorted_association_options_find was changed on activescaffold long time ago, I forgot to update batch to use something like :select form_ui:

collection_select(:record, method, select_options, :id, column.options[:label_method] || :to_label, options, html_options)
