### ISSUE TITLE
Does not Work with Rails 5.1

### ISSUE THREAD

**Issue by Ladeburger** [activescaffold/active_scaffold_batch#6]
If one includes active_scaffold_batch in the Gemfile, the Application stops with:

`couldn't find file 'active_scaffold_batch' with type 'application/javascript'
Checked in these paths: 
  /home/jan/src/cmdbfe/app/assets/images
 ...`

**Comment by lulalala** [comment]
bump

**Comment by scambra** [comment]
I have used It in an app with all rails 5.x versions and 6.x versions and didn't get that error, so It should be working
